GetNewsArticlesUseCase / GetNewsArticlesByIdUseCase IntegrationTests (#27)
* implement structure for getnewsarticles, move shared doubles into core, compositionroot in sharedtests, make types internalsvisibleto sharedtests

* add integration_tests action and share build steps across both unit_test_format and integration_tests

* attempt cache packages

* attempt fix pathing

* fix pathing as local action

* fix to action not plural

* checkout then action

* explicit on shell bash

* pass token down

* sln relative path

* remove no build to proof

* fix pathing

* pathing

* correct to hyphens than /

* make sure we collect cov

* revert gulpfile path change

* fix gulp and format

* require build

* call build in build action, nobuild in tests

* newline args

* pass explicit test proejcts

* exclude core.sharedtests

* use github action to display codecov in pipeline and fail if falls below

* pass build config down

* fix bug in containername/dbname order. Implement getnewsarticlesbyid

* remove buildconfiguration off restore

* id clash with lorem?

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,79 +6,122 @@ permissions:
 
 on:
   push:
+    branches: [main]
+  pull_request:
+    branches: [main]
+
+env:
+  buildConfiguration: Release
+  solutionDirectory: ./DfE.GIAP.All
 
 jobs:
-  build:
+  build_unittest:
     runs-on: ubuntu-latest
-
-    env:
-      buildConfiguration: Release
-      solutionDirectory: ./DfE.GIAP.All
-
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    - name: Setup Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: '12'
+      - name: Build
+        uses: ./.github/actions/build
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Setup .NET SDK from global.json
-      uses: actions/setup-dotnet@v4
+      - name: Run unit tests
+        run: |
+          for proj in \
+            ./DfE.GIAP.Common.Tests/DfE.GIAP.Common.Tests.csproj \
+            ./DfE.GIAP.Service.Tests/DfE.GIAP.Service.Tests.csproj \
+            ./DfE.GIAP.Web.Tests/DfE.GIAP.Web.Tests.csproj \
+            ./DfE.GIAP.Core.UnitTests/DfE.GIAP.Core.UnitTests.csproj
+          do
+            echo "Running tests for $proj"
+            dotnet test "$proj" \
+              --verbosity normal \
+              --collect:"XPlat Code Coverage" \
+              -p:CoverletOutputFormat=cobertura \
+              -p:CoverletOutput=./TestResults/
+          done
+        working-directory: ${{ env.solutionDirectory }}
 
-    - name: Install NuGet
-      uses: NuGet/setup-nuget@v2
+      - name: Install ReportGenerator tool
+        run: dotnet tool install --tool-path ./tools dotnet-reportgenerator-globaltool --version 4.5.8
+        working-directory: ${{ env.solutionDirectory }}
 
-    - name: npm install
-      run: npm install
-      working-directory: ${{ env.solutionDirectory }}/DfE.GIAP.Web
+      - name: Generate test coverage reports
+        run: ./tools/reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:./coverlet/reports" "-reporttypes:Cobertura" "-assemblyfilters:-DfE.GIAP.Web.Views;-DfE.GIAP.Service.Tests;-DfE.GIAP.Core.SharedTests;"
+        working-directory: ${{ env.solutionDirectory }}
 
-    - name: Add DfEDigital NuGet Feed
-      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name dfedigital "https://nuget.pkg.github.com/DFE-Digital/index.json"
+      - name: Upload test coverage reports
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-report
+          path: ${{ env.solutionDirectory }}/coverlet/reports/Cobertura.xml
 
-    - name: Restore NuGet packages
-      run: dotnet restore *.sln
-      working-directory: ${{ env.solutionDirectory }}
-      
-    - name: Build solution
-      run: dotnet build *.sln --configuration ${{ env.buildConfiguration }} --no-restore -p:SkipInvalidConfigurations=true 
-       
-      # These are specific to windows-latest msdeploy so have been removed temporarily
-      #-p:DesktopBuildPackageLocation="${{ github.workspace }}\WebApp.zip"
-      # -p:DeployOnBuild=true -p:WebPublishMethod=Package -p:PackageAsSingleFile=true -p:DeployIisAppPath="Default Web Site"
-      working-directory: ${{ env.solutionDirectory }}
-      
-    - name: Run unit tests
-      run: dotnet test *.sln --configuration ${{ env.buildConfiguration }} --collect "XPlat Code coverage" -- RunConfiguration.DisableAppDomain=true
-      working-directory: ${{ env.solutionDirectory }}
-      
-    - name: Install ReportGenerator tool
-      run: dotnet tool install --tool-path ./tools dotnet-reportgenerator-globaltool --version 4.5.8
-      working-directory: ${{ env.solutionDirectory }}
+      - name: Summarise code coverage
+        uses: irongut/CodeCoverageSummary@v1.3.0
+        with:
+          filename: ${{ env.solutionDirectory }}/coverlet/reports/Cobertura.xml
+          badge: true
+          fail_below_min: true
+          format: markdown
+          hide_branch_rate: false
+          hide_complexity: true
+          indicators: true
+          output: both
+          thresholds: '60 80'
 
-    - name: Generate test coverage reports
-      run: ./tools/reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:./coverlet/reports" "-reporttypes:Cobertura" "-assemblyfilters:-DfE.GIAP.Web.Views;-DfE.GIAP.Service.Tests"
-      working-directory: ${{ env.solutionDirectory }}
+      - name: Run gulp
+        run: |
+          npm install -g gulp
+          gulp default --gulpfile DfE.GIAP.Web/gulpfile.js --cwd DfE.GIAP.Web 
+        working-directory: ${{ env.solutionDirectory }}
 
-    - name: Upload test coverage reports
-      uses: actions/upload-artifact@v4
-      with:
-        name: coverage-report
-        path: ${{ env.solutionDirectory }}/coverlet/reports/Cobertura.xml
-
-    - name: Run gulp
-      run: |
-        npm install -g gulp
-        gulp default --gulpfile DfE.GIAP.Web/gulpfile.js --cwd DfE.GIAP.Web 
-      working-directory: ${{ env.solutionDirectory }}
-      
 #    - name: Upload build artifact
 #      uses: actions/upload-artifact@v4
 #      with:
 #        name: WebApp
 #        path: WebApp.zip
 
-    - name: Verify formatting
-      run: dotnet format --include DfE.GIAP.Core/ DfE.GIAP.Core.UnitTests/ --verify-no-changes
-      working-directory: ./DfE.GIAP.All
+      - name: Verify formatting
+        run: dotnet format --include DfE.GIAP.Core/ DfE.GIAP.Core.UnitTests/ --verify-no-changes
+        working-directory: ${{ env.solutionDirectory }}
+
+  integration_tests:
+    runs-on: ubuntu-latest
+    needs: build_unittest
+    services:
+      cosmosdb:
+        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
+        ports:
+          - 8081:8081
+          - 10250-10255:10250-10255
+        env:
+          AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 5
+          AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: true
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Build
+        uses: ./.github/actions/build
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Install CosmosDb Emulator TLS certificate
+        run: |
+          retry_count=0
+          max_retry_count=10
+          until sudo curl --insecure --silent --fail --show-error "https://localhost:8081/_explorer/emulator.pem" --output "/usr/local/share/ca-certificates/cosmos-db-emulator.crt"; do
+            if [ $retry_count -eq $max_retry_count ]; then
+              echo "Failed to download certificate after $retry_count attempts."
+              exit 1
+            fi
+            echo "Failed to download certificate. Retrying in 5 seconds..."
+            sleep 5
+            retry_count=$((retry_count+1))
+          done
+          sudo update-ca-certificates
+
+      - name: Run Integration Tests
+        run: dotnet test ./DfE.GIAP.All/DfE.GIAP.Core.IntegrationTests/DfE.GIAP.Core.IntegrationTests.csproj --no-build --verbosity normal
